baseurl: /
languageCode: en-us
title: Vashishtha Jogi
enableRobotsTXT: true
disableAliases: true
# googleAnalytics: UA-4839600-11

pagination:
  pagerSize: 10

markup:
  highlight:
    style: monokai
    lineNos: false
    noClasses: false

params:
  name: Vashishtha Jogi
  description: ''
  bio: thoughts about programming and photography
  twitter: VashishthaJogi
  enableRSS: true
  displayPostTags: true
  customCSS: []
  customJS: []
  home: ''
  subscribe: subscribe
  olderPosts: ''
  newerPosts: ''
  readMore: ''
  copyright: ''
  aboutAuthor: I'm an blogger.
  tweet: ''
  share: ''
  title404: ''
  subtitle404: ''
  disallow_search_engines: false
  mainSections:
    - posts

outputFormats:
  json:
    mediaType: application/json
    baseName: index
    isPlainText: true

outputs:
  home:
    - HTML
    - JSON
  page:
    - HTML
